# MS-DOS64 – 64-bit BIOS boot build (Phase 12 - stack & ABI)
# Phase 12: Stack/ABI hardening (RSP 16B, System V RDI/RSI/RDX/RCX/R8/R9, callee-saved, canary, IST reserve) + all prior phases
# Requires: nasm >=2.15, ld (binutils), qemu or bochs
BUILD := build
SRC_BOOT := src/boot
SRC_KERNEL := src/kernel
SRC_DRIVERS := src/drivers
SRC_LIB := src/lib

# Disk layout — SINGLE SOURCE OF TRUTH (fixed values, not overridable).
# Canonical numbers live ONLY in this block. The build generates
# $(BUILD)/include/layout.inc (NASM %defines) which src/boot/stage2.asm and
# include/fs.inc %include, and passes the same values explicitly to
# tools/mkfat12.py on every stamp (no script-side defaults).
# `make check-layout` is a prerequisite of both disk images, so it runs on
# every `make all` with no separate invocation; it validates the generated
# file, the source %includes, the explicit stamper args, and the arithmetic
# invariants (kernel extent ends at/before VOL_LBA; volume end fits IMG_MB).
# Command-line overrides (e.g. `make VOL_LBA=600`) are rejected below: with
# per-layer duplicates gone, a relocated build would need a new canonical
# block, not a half-applied flag. To change the layout, edit this block and
# rebuild from clean.
IMG_MB := 10
IMG_SECTOR_SIZE := 512
VOL_LBA := 512
VOL_SECTORS := 2880
KERNEL_LBA := 16
KERNEL_SECTORS := 176
LAYOUT_INC := $(BUILD)/include/layout.inc

# Reject unsupported layout overrides. (Environment values are already
# ignored by the := assignments above; command-line assignments still win
# in GNU make, so fail fast instead of building a split-brain image.)
ifeq ($(origin IMG_MB),command line)
$(error layout override rejected: IMG_MB is single-sourced in the Makefile disk-layout block)
endif
ifeq ($(origin IMG_SECTOR_SIZE),command line)
$(error layout override rejected: IMG_SECTOR_SIZE is single-sourced in the Makefile disk-layout block)
endif
ifeq ($(origin VOL_LBA),command line)
$(error layout override rejected: VOL_LBA is single-sourced in the Makefile disk-layout block (got '$(VOL_LBA)'))
endif
ifeq ($(origin VOL_SECTORS),command line)
$(error layout override rejected: VOL_SECTORS is single-sourced in the Makefile disk-layout block (got '$(VOL_SECTORS)'))
endif
ifeq ($(origin KERNEL_LBA),command line)
$(error layout override rejected: KERNEL_LBA is single-sourced in the Makefile disk-layout block (got '$(KERNEL_LBA)'))
endif
ifeq ($(origin KERNEL_SECTORS),command line)
$(error layout override rejected: KERNEL_SECTORS is single-sourced in the Makefile disk-layout block (got '$(KERNEL_SECTORS)'))
endif

NASM := nasm
# -Wall enables all assembler warnings; -Werror promotes them to errors so
# build warnings fail the build instead of scrolling past. Explicit silences
# below cover relocations that are benign by design (linker-resolved or
# intended absolute addresses) and would otherwise make -Wall unusable:
#   -Wno-reloc-abs-word: 16-bit absolute addressing in the ORG'd boot code
#     (intended [boot_drive]/DAP/msg references at 0x7C00/0x7E00).
#   -Wno-reloc-abs-dword/-qword (BIN): GDT descriptors and page-table setup
#     use intentional absolute addresses in the flat binary.
#   -Wno-reloc-rel-dword/-abs-qword (ELF): cross-section calls/jmps and
#     64-bit absolute symbol loads in kernel objects; resolved by ld.
# (--warn-section-align stays omitted for ld: the flat-binary linker script
# intentionally shifts section starts.)
NASM_BIN := $(NASM) -f bin -Wall -Werror -Wno-reloc-abs-word -Wno-reloc-abs-dword -Wno-reloc-abs-qword
NASM_ELF := $(NASM) -f elf64 -g -F dwarf -Wall -Werror -Wno-reloc-abs-word -Wno-reloc-rel-dword -Wno-reloc-abs-qword -I.
# Self-test control (docs/05 §7): default full build runs the suite.
#   Full: -DRUN_SELFTEST (default) -> _start runs tests 1..83 then shell.
#   Lean: -DSKIP_SELFTEST -> _start skips suite, minimal init, shell direct.
# Override with `make NASM_DEFS=-DSKIP_SELFTEST` or `make lean`.
NASM_DEFS ?= -DRUN_SELFTEST

# Kernel objects: all kernel, drivers, lib .asm files -> .o
KERNEL_SRCS := $(wildcard $(SRC_KERNEL)/*.asm) $(wildcard $(SRC_DRIVERS)/*.asm) $(wildcard $(SRC_LIB)/*.asm)
KERNEL_OBJS := $(patsubst %.asm,$(BUILD)/%.o,$(KERNEL_SRCS))

# Lean kernel objects (separate dir so full/lean can coexist)
LEAN_BUILD := $(BUILD)/lean
LEAN_OBJS := $(patsubst %.asm,$(LEAN_BUILD)/%.o,$(KERNEL_SRCS))

# Ensure build dirs exist for nested paths
KERNEL_OBJ_DIRS := $(sort $(dir $(KERNEL_OBJS)))
LEAN_OBJ_DIRS := $(sort $(dir $(LEAN_OBJS)))

all: $(BUILD)/dos64.img

lean: $(BUILD)/dos64-lean.img

$(BUILD):
	mkdir -p $(BUILD)

# Generated disk-layout include: the ONLY artifact carrying layout numbers
# into NASM sources (repo-root-relative %include "build/include/layout.inc"
# from src/boot/stage2.asm and include/fs.inc). Regenerated whenever this
# Makefile changes; consumers rebuild via the prerequisites below.
$(LAYOUT_INC): Makefile | $(BUILD)
	@mkdir -p $(dir $@)
	@{ \
		echo '; Generated by Makefile - do not edit. Canonical disk layout'; \
		echo '; (single source of truth: Makefile disk-layout block).'; \
		echo '%ifndef LAYOUT_INC'; \
		echo '%define LAYOUT_INC'; \
		echo '%define IMG_MB $(IMG_MB)'; \
		echo '%define IMG_SECTOR_SIZE $(IMG_SECTOR_SIZE)'; \
		echo '%define KERNEL_LBA $(KERNEL_LBA)'; \
		echo '%define KERNEL_SECTORS $(KERNEL_SECTORS)'; \
		echo '%define VOL_LBA $(VOL_LBA)'; \
		echo '%define VOL_SECTORS $(VOL_SECTORS)'; \
		echo '%define FS_VOL_LBA $(VOL_LBA)'; \
		echo '%define FS_VOL_TOTSEC $(VOL_SECTORS)'; \
		echo '%endif'; \
	} > $@.tmp
	@mv $@.tmp $@
	@echo "Generated $@"

# Helper to create build subdirectories
$(KERNEL_OBJ_DIRS):
	mkdir -p $@

$(LEAN_OBJ_DIRS):
	mkdir -p $@

# Boot images
$(BUILD)/mbr.bin: $(SRC_BOOT)/mbr.asm | $(BUILD)
	$(NASM_BIN) $< -o $@
	@test $$(stat -c %s $@) -eq 512 || (echo "MBR must be 512 bytes"; exit 1)
	@tail -c2 $@ | od -An -tx1 | grep -q "55 aa" || (echo "Missing boot signature 55AA"; exit 1)

$(BUILD)/stage2.bin: $(SRC_BOOT)/stage2.asm $(SRC_BOOT)/gdt.asm $(LAYOUT_INC) | $(BUILD)
	$(NASM_BIN) $< -o $@
	@echo "Stage2 built: $$(stat -c %s $@) bytes"

# Rule for kernel .o from .asm (with include path)
$(BUILD)/%.o: %.asm $(LAYOUT_INC) | $(KERNEL_OBJ_DIRS)
	$(NASM_ELF) $(NASM_DEFS) $< -o $@

$(LEAN_BUILD)/%.o: %.asm $(LAYOUT_INC) | $(LEAN_OBJ_DIRS)
	$(NASM_ELF) -DSKIP_SELFTEST $< -o $@

$(BUILD)/kernel.elf: $(KERNEL_OBJS) linker.ld | $(BUILD)
	ld -T linker.ld -o $@ $(BUILD)/src/kernel/main.o $(filter-out $(BUILD)/src/kernel/main.o,$(KERNEL_OBJS)) -nostdlib --fatal-warnings -Map=$(BUILD)/kernel.map || (cat $(BUILD)/kernel.map; exit 1)
	@echo "Kernel linked: $$(stat -c %s $@) bytes, objects: $(words $(KERNEL_OBJS))"

$(BUILD)/kernel.bin: $(BUILD)/kernel.elf | $(BUILD)
	objcopy -O binary $< $@
	@echo "Kernel binary: $$(stat -c %s $@) bytes ($$(expr $$(stat -c %s $@) / 512) sectors)"
	@test $$(stat -c %s $@) -le $$(expr $(KERNEL_SECTORS) \* $(IMG_SECTOR_SIZE)) || (echo "Kernel too large for $(KERNEL_SECTORS) sectors! Increase KERNEL_SECTORS in the Makefile disk-layout block"; exit 1)

$(BUILD)/dos64.img: $(BUILD)/mbr.bin $(BUILD)/stage2.bin $(BUILD)/kernel.bin check-layout check-kbc check-serial | $(BUILD)
	dd if=/dev/zero of=$@ bs=1M count=$(IMG_MB) status=none
	dd if=$(BUILD)/mbr.bin of=$@ conv=notrunc status=none
	dd if=$(BUILD)/stage2.bin of=$@ bs=$(IMG_SECTOR_SIZE) seek=1 conv=notrunc status=none
	dd if=$(BUILD)/kernel.bin of=$@ bs=$(IMG_SECTOR_SIZE) seek=$(KERNEL_LBA) conv=notrunc status=none
	python3 -W error tools/mkfat12.py --vol-lba $(VOL_LBA) --vol-totsec $(VOL_SECTORS) --sector-size $(IMG_SECTOR_SIZE) --kernel-lba $(KERNEL_LBA) --kernel-sectors $(KERNEL_SECTORS) $@
	@echo "Created $@ ($$(stat -c %s $@) bytes)"

$(LEAN_BUILD)/kernel.elf: $(LEAN_OBJS) linker.ld | $(BUILD)
	ld -T linker.ld -o $@ $(LEAN_BUILD)/src/kernel/main.o $(filter-out $(LEAN_BUILD)/src/kernel/main.o,$(LEAN_OBJS)) -nostdlib --fatal-warnings -Map=$(LEAN_BUILD)/kernel.map || (cat $(LEAN_BUILD)/kernel.map; exit 1)
	@echo "Lean kernel linked: $$(stat -c %s $@) bytes, objects: $(words $(LEAN_OBJS))"

$(LEAN_BUILD)/kernel.bin: $(LEAN_BUILD)/kernel.elf | $(BUILD)
	objcopy -O binary $< $@
	@echo "Lean kernel binary: $$(stat -c %s $@) bytes ($$(expr $$(stat -c %s $@) / 512) sectors)"
	@test $$(stat -c %s $@) -le $$(expr $(KERNEL_SECTORS) \* $(IMG_SECTOR_SIZE)) || (echo "Lean kernel too large for $(KERNEL_SECTORS) sectors! Increase KERNEL_SECTORS in the Makefile disk-layout block"; exit 1)

$(BUILD)/dos64-lean.img: $(BUILD)/mbr.bin $(BUILD)/stage2.bin $(LEAN_BUILD)/kernel.bin check-layout check-kbc check-serial | $(BUILD)
	dd if=/dev/zero of=$@ bs=1M count=$(IMG_MB) status=none
	dd if=$(BUILD)/mbr.bin of=$@ conv=notrunc status=none
	dd if=$(BUILD)/stage2.bin of=$@ bs=$(IMG_SECTOR_SIZE) seek=1 conv=notrunc status=none
	dd if=$(LEAN_BUILD)/kernel.bin of=$@ bs=$(IMG_SECTOR_SIZE) seek=$(KERNEL_LBA) conv=notrunc status=none
	python3 -W error tools/mkfat12.py --vol-lba $(VOL_LBA) --vol-totsec $(VOL_SECTORS) --sector-size $(IMG_SECTOR_SIZE) --kernel-lba $(KERNEL_LBA) --kernel-sectors $(KERNEL_SECTORS) $@
	@echo "Created $@ ($$(stat -c %s $@) bytes)"

# Verify the single-sourced layout before any image bytes are written.
# Prerequisite of both disk images, so every `make all` runs this first.
# Fails the build with a clear message instead of producing a
# silently-corrupt image. Checks:
#   1. build/include/layout.inc carries the canonical Makefile values
#      (bootloader/kernel constants and stamper args cannot drift apart).
#   2. stage2.asm / include/fs.inc consume the generated file and no longer
#      hardcode layout numbers.
#   3. tools/mkfat12.py accepts every layout value explicitly and both image
#      recipes pass the canonical values.
#   4. Kernel extent [KERNEL_LBA, +KERNEL_SECTORS) ends at/before VOL_LBA.
#   5. Volume end fits inside the IMG_MB image.
check-layout: $(LAYOUT_INC)
	@test "$$(grep -E '^%define IMG_SECTOR_SIZE' $(LAYOUT_INC) | awk '{print $$3}')" = "$(IMG_SECTOR_SIZE)" || (echo "layout drift: Makefile IMG_SECTOR_SIZE=$(IMG_SECTOR_SIZE) != $(LAYOUT_INC)"; exit 1)
	@test "$$(grep -E '^%define KERNEL_LBA' $(LAYOUT_INC) | awk '{print $$3}')" = "$(KERNEL_LBA)" || (echo "layout drift: Makefile KERNEL_LBA=$(KERNEL_LBA) != $(LAYOUT_INC)"; exit 1)
	@test "$$(grep -E '^%define KERNEL_SECTORS' $(LAYOUT_INC) | awk '{print $$3}')" = "$(KERNEL_SECTORS)" || (echo "layout drift: Makefile KERNEL_SECTORS=$(KERNEL_SECTORS) != $(LAYOUT_INC)"; exit 1)
	@test "$$(grep -E '^%define VOL_LBA' $(LAYOUT_INC) | awk '{print $$3}')" = "$(VOL_LBA)" || (echo "layout drift: Makefile VOL_LBA=$(VOL_LBA) != $(LAYOUT_INC)"; exit 1)
	@test "$$(grep -E '^%define VOL_SECTORS' $(LAYOUT_INC) | awk '{print $$3}')" = "$(VOL_SECTORS)" || (echo "layout drift: Makefile VOL_SECTORS=$(VOL_SECTORS) != $(LAYOUT_INC)"; exit 1)
	@test "$$(grep -E '^%define FS_VOL_LBA' $(LAYOUT_INC) | awk '{print $$3}')" = "$(VOL_LBA)" || (echo "layout drift: $(LAYOUT_INC) FS_VOL_LBA alias != VOL_LBA=$(VOL_LBA)"; exit 1)
	@test "$$(grep -E '^%define FS_VOL_TOTSEC' $(LAYOUT_INC) | awk '{print $$3}')" = "$(VOL_SECTORS)" || (echo "layout drift: $(LAYOUT_INC) FS_VOL_TOTSEC alias != VOL_SECTORS=$(VOL_SECTORS)"; exit 1)
	@grep -q 'build/include/layout.inc' $(SRC_BOOT)/stage2.asm || (echo "layout drift: $(SRC_BOOT)/stage2.asm must %include build/include/layout.inc"; exit 1)
	@grep -q 'build/include/layout.inc' include/fs.inc || (echo "layout drift: include/fs.inc must %include build/include/layout.inc"; exit 1)
	@! grep -Eq '^[[:space:]]*KERNEL_LBA[[:space:]]+equ' $(SRC_BOOT)/stage2.asm || (echo "layout drift: $(SRC_BOOT)/stage2.asm hardcodes KERNEL_LBA; use build/include/layout.inc"; exit 1)
	@! grep -Eq '^[[:space:]]*KERNEL_SECTORS[[:space:]]+equ' $(SRC_BOOT)/stage2.asm || (echo "layout drift: $(SRC_BOOT)/stage2.asm hardcodes KERNEL_SECTORS; use build/include/layout.inc"; exit 1)
	@! grep -Eq '^%define[[:space:]]+FS_VOL_LBA' include/fs.inc || (echo "layout drift: include/fs.inc hardcodes FS_VOL_LBA; use build/include/layout.inc"; exit 1)
	@! grep -Eq '^%define[[:space:]]+FS_VOL_TOTSEC' include/fs.inc || (echo "layout drift: include/fs.inc hardcodes FS_VOL_TOTSEC; use build/include/layout.inc"; exit 1)
	@grep -q -- '--vol-lba' tools/mkfat12.py || (echo "layout drift: tools/mkfat12.py must accept --vol-lba explicitly"; exit 1)
	@grep -q -- '--vol-totsec' tools/mkfat12.py || (echo "layout drift: tools/mkfat12.py must accept --vol-totsec explicitly"; exit 1)
	@grep -q -- '--sector-size' tools/mkfat12.py || (echo "layout drift: tools/mkfat12.py must accept --sector-size explicitly"; exit 1)
	@grep -q -- '--kernel-lba' tools/mkfat12.py || (echo "layout drift: tools/mkfat12.py must accept --kernel-lba explicitly"; exit 1)
	@grep -q -- '--kernel-sectors' tools/mkfat12.py || (echo "layout drift: tools/mkfat12.py must accept --kernel-sectors explicitly"; exit 1)
	@grep -q -- '--vol-lba $$(VOL_LBA)' Makefile || (echo "layout drift: dos64.img recipe must pass --vol-lba $(VOL_LBA) explicitly"; exit 1)
	@test $$(( $(KERNEL_LBA) + $(KERNEL_SECTORS) )) -le $(VOL_LBA) || (echo "layout overlap: kernel extent LBA $(KERNEL_LBA)+$(KERNEL_SECTORS) overlaps volume LBA $(VOL_LBA)"; exit 1)
	@test $$(( ($(VOL_LBA) + $(VOL_SECTORS)) * $(IMG_SECTOR_SIZE) )) -le $$(( $(IMG_MB) * 1024 * 1024 )) || (echo "layout drift: volume end LBA $$(( $(VOL_LBA) + $(VOL_SECTORS) )) exceeds IMG_MB=$(IMG_MB) image"; exit 1)
	@echo "Layout OK: img=$(IMG_MB)MiB secsiz=$(IMG_SECTOR_SIZE) vol_lba=$(VOL_LBA) vol_sectors=$(VOL_SECTORS) kernel_lba=$(KERNEL_LBA) kernel_sectors=$(KERNEL_SECTORS)"

# Negative layout checks — same paths `make all` uses, but with bad inputs
# that must be rejected. Deterministic, no emulator, no timing.
# Verifies: (1) command-line layout overrides are rejected by the
# single-source guard (same error path a relocated `make VOL_LBA=...`
# would hit); (2) the stamper (tools/mkfat12.py, same explicit flags the
# image recipes pass) rejects an overlapping kernel/volume extent and a
# non-512 sector size instead of stamping a corrupt image.
# Run manually (`make check-layout-neg`); `make all` already runs the
# positive `check-layout` on every build, and test 82 locks the same
# arithmetic (kernel_end<=VOL_LBA, volume fits IMG_MB) at runtime.
check-layout-neg: $(BUILD)/mbr.bin
	@echo "Layout negative checks (same paths as make all)..."
	@! $(MAKE) --no-print-directory VOL_LBA=600 check-layout >/dev/null 2>&1 || (echo "layout-neg FAIL: VOL_LBA override not rejected"; exit 1)
	@echo "  override rejection OK"
	@rm -f $(BUILD)/.layout-neg.img
	@dd if=/dev/zero of=$(BUILD)/.layout-neg.img bs=1M count=$(IMG_MB) status=none
	@! python3 -W error tools/mkfat12.py --vol-lba $(VOL_LBA) --vol-totsec $(VOL_SECTORS) --sector-size $(IMG_SECTOR_SIZE) --kernel-lba $(VOL_LBA) --kernel-sectors $(KERNEL_SECTORS) $(BUILD)/.layout-neg.img >/dev/null 2>&1 || (echo "layout-neg FAIL: overlapping kernel/volume not rejected by stamper"; exit 1)
	@echo "  stamper overlap rejection OK"
	@! python3 -W error tools/mkfat12.py --vol-lba $(VOL_LBA) --vol-totsec $(VOL_SECTORS) --sector-size 1024 --kernel-lba $(KERNEL_LBA) --kernel-sectors $(KERNEL_SECTORS) $(BUILD)/.layout-neg.img >/dev/null 2>&1 || (echo "layout-neg FAIL: sector-size 1024 not rejected by stamper"; exit 1)
	@echo "  stamper sector-size rejection OK"
	@rm -f $(BUILD)/.layout-neg.img
	@echo "Layout negative checks OK"

# Bounded-KBC regression check — source-level assertion that the boot
# keyboard-controller waits cannot spin forever. Deterministic, host-side,
# no emulator: greps the same NASM sources `make all` assembles.
# For each of mbr.asm / stage2.asm it verifies:
#   1. a `kbc_wait_timeout:` helper exists (the bounded helper);
#   2. the helper loads a finite counter from a KBC_TIMEOUT* bound
#      (`mov cx, KBC_TIMEOUT...`) and decrements it (`dec cx`);
#   3. the helper has an explicit failure branch returning CF=1 (`stc`)
#      alongside the success branch (`clc`);
#   4. every KBC command/status wait checks the return (`jc ...` after
#      each `call kbc_wait_timeout` — 3 sites per stage);
#   5. no unbounded wait remains (`jnz` directly to a kbc_wait* label).
# A timeout is a FALLBACK condition (fast-A20 via port 0x92 is primary),
# not boot-fatal: callers skip the remaining KBC outs, re-assert fast A20,
# print a diagnostic, and continue boot. Prerequisite of both disk images,
# so every `make all` runs this with no separate invocation.
check-kbc:
	@for f in $(SRC_BOOT)/mbr.asm $(SRC_BOOT)/stage2.asm; do \
		grep -q 'kbc_wait_timeout:' $$f || (echo "kbc FAIL: $$f missing kbc_wait_timeout helper"; exit 1); \
		grep -q 'KBC_TIMEOUT' $$f || (echo "kbc FAIL: $$f missing KBC_TIMEOUT bound"; exit 1); \
		grep -Eq 'mov[[:space:]]+cx,[[:space:]]*KBC_TIMEOUT' $$f || (echo "kbc FAIL: $$f helper does not load finite CX counter"; exit 1); \
		grep -Eq 'dec[[:space:]]+cx' $$f || (echo "kbc FAIL: $$f helper has no decrementing counter"; exit 1); \
		grep -q '[[:space:]]stc' $$f || (echo "kbc FAIL: $$f helper has no explicit failure branch (stc/CF=1)"; exit 1); \
		grep -q '[[:space:]]clc' $$f || (echo "kbc FAIL: $$f helper has no success branch (clc/CF=0)"; exit 1); \
		test $$(grep -c 'call kbc_wait_timeout' $$f) -eq 3 || (echo "kbc FAIL: $$f must check 3 KBC waits (found $$(grep -c 'call kbc_wait_timeout' $$f))"; exit 1); \
		test $$(grep -c 'jc .kbc_skip' $$f) -eq 3 || (echo "kbc FAIL: $$f must branch on timeout after each wait (found $$(grep -c 'jc .kbc_skip' $$f) jc)"; exit 1); \
		! grep -Eq 'jnz[[:space:]]+kbc_wait' $$f || (echo "kbc FAIL: $$f still contains unbounded jnz to kbc_wait*"; exit 1); \
	done
	@echo "KBC wait OK: bounded kbc_wait_timeout (CX counter + CF=1 timeout) with fallback in mbr + stage2"

# Bounded-serial regression check — source-level assertion that no serial
# transmit path can spin forever on UART readiness. Deterministic,
# host-side, no emulator: greps the same NASM sources `make all` assembles.
# Serial is optional best-effort diagnostic I/O (VGA is authoritative): every
# TX site must use a bounded helper that drops the character on timeout
# (CF=1) instead of hanging boot, the suite, or the shell.
# Verifies:
#   1. Boot (mbr/stage2): a `serial_try_putc*` helper exists with a finite
#      `SERIAL_TIMEOUT*` counter (`mov cx, ...`, `dec cx`) and explicit
#      drop (`stc`/CF=1) + success (`clc`/CF=0) branches; the print path
#      calls it; the old unbounded `jz .wait_ser*` spin is gone.
#   2. Kernel: `main.asm` provides the single reusable `serial_try_putc64`
#      (finite `mov ecx, SERIAL_TIMEOUT` + `dec ecx`, `stc`/`clc`), and
#      `serial_print64` calls it (CF ignored: drop and continue).
#   3. All other kernel TX sites (shell/cmd/selftest/stack) call the shared
#      helper and perform no direct `mov dx, 0x3FD` UART poll of their own.
#   4. The AUX backend (`syscall64.asm com1_write_char`) stays bounded too
#      (`dec rcx` budget + `stc` timeout); the RX poll (`com1_read_char`)
#      is single-shot non-blocking by design.
# Normal QEMU/Bochs output is unchanged: the timeout budget covers 16550
# baud per-byte delay, and a missing UART reads LSR=0xFF (THRE set) so the
# first poll succeeds. Prerequisite of both disk images, so every
# `make all` runs this with no separate invocation.
check-serial:
	@for f in $(SRC_BOOT)/mbr.asm $(SRC_BOOT)/stage2.asm; do \
		grep -q 'serial_try_putc' $$f || (echo "serial FAIL: $$f missing serial_try_putc helper"; exit 1); \
		grep -q 'SERIAL_TIMEOUT' $$f || (echo "serial FAIL: $$f missing SERIAL_TIMEOUT bound"; exit 1); \
		grep -Eq 'mov[[:space:]]+cx,[[:space:]]*SERIAL_TIMEOUT' $$f || (echo "serial FAIL: $$f helper does not load finite CX counter"; exit 1); \
		grep -Eq 'dec[[:space:]]+cx' $$f || (echo "serial FAIL: $$f helper has no decrementing counter"; exit 1); \
		grep -q '[[:space:]]stc' $$f || (echo "serial FAIL: $$f helper has no drop branch (stc/CF=1)"; exit 1); \
		grep -q '[[:space:]]clc' $$f || (echo "serial FAIL: $$f helper has no success branch (clc/CF=0)"; exit 1); \
		grep -q 'call serial_try_putc' $$f || (echo "serial FAIL: $$f print path does not use bounded helper"; exit 1); \
		! grep -Eq 'jz[[:space:]]+\.wait_ser' $$f || (echo "serial FAIL: $$f still contains unbounded jz to .wait_ser*"; exit 1); \
	done
	@grep -q 'global serial_try_putc64' $(SRC_KERNEL)/main.asm || (echo "serial FAIL: main.asm missing shared serial_try_putc64"; exit 1)
	@grep -q 'SERIAL_TIMEOUT equ' $(SRC_KERNEL)/main.asm || (echo "serial FAIL: main.asm missing SERIAL_TIMEOUT bound"; exit 1)
	@grep -Eq 'mov[[:space:]]+ecx,[[:space:]]*SERIAL_TIMEOUT' $(SRC_KERNEL)/main.asm || (echo "serial FAIL: serial_try_putc64 does not load finite ECX counter"; exit 1)
	@grep -Eq 'dec[[:space:]]+ecx' $(SRC_KERNEL)/main.asm || (echo "serial FAIL: serial_try_putc64 has no decrementing counter"; exit 1)
	@grep -q 'call serial_try_putc64' $(SRC_KERNEL)/main.asm || (echo "serial FAIL: serial_print64 does not use bounded helper"; exit 1)
	@for f in $(SRC_KERNEL)/shell64.asm $(SRC_KERNEL)/cmd64.asm $(SRC_KERNEL)/selftest64.asm $(SRC_KERNEL)/stack64.asm; do \
		grep -q 'call serial_try_putc64' $$f || (echo "serial FAIL: $$f does not use shared serial_try_putc64"; exit 1); \
		! grep -q 'mov dx, 0x3FD' $$f || (echo "serial FAIL: $$f still polls UART directly (must go through serial_try_putc64)"; exit 1); \
	done
	@grep -Eq 'dec[[:space:]]+rcx' $(SRC_KERNEL)/syscall64.asm || (echo "serial FAIL: syscall64.asm com1_write_char lost its bounded counter"; exit 1)
	@echo "Serial TX OK: bounded serial_try_putc (boot) + serial_try_putc64 (kernel, drop on timeout) in mbr + stage2 + main/shell/cmd/selftest/stack"

run-bochs: $(BUILD)/dos64.img
	rm -f $(BUILD)/dos64.img.lock bochs.log serial.log
	bochs -f bochsrc.txt -q

run-qemu: $(BUILD)/dos64.img
	qemu-system-x86_64 -drive file=$(BUILD)/dos64.img,format=raw -serial stdio

run-qemu-lean: $(BUILD)/dos64-lean.img
	qemu-system-x86_64 -drive file=$(BUILD)/dos64-lean.img,format=raw -serial stdio

clean:
	rm -rf $(BUILD)/*.bin $(BUILD)/*.o $(BUILD)/*.img $(BUILD)/*.elf $(BUILD)/*.map $(BUILD)/*.lock
	rm -rf $(BUILD)/src $(BUILD)/lean $(BUILD)/include

.PHONY: all lean clean run-bochs run-qemu run-qemu-lean check-layout check-layout-neg check-kbc check-serial
